# SPDX-FileCopyrightText: 2020 Globacap
#
# SPDX-License-Identifier: MPL-2.0
<<: !include "./hpack/module.yaml"

name:                globacap
version:             0.1.0

extra-source-files:
- README.md

category:            Blockchain
description:
  FA1.2-based token contract (called `Holdings`) with
  `Safelist` contract that contains information about whitelisted
  and blacklisted investors.

verbatim:
  cabal-version: 2.2

library:
  <<: *lib-common

  default-extensions:
    - RebindableSyntax

  dependencies:
    - base-noprelude >= 4.7 && < 5
    - containers
    - fmt
    - indigo
    - lorentz
    - morley
    - morley-ledgers
    - morley-prelude

executables:
  globacap:
    <<: *exec-common

    dependencies:
      - containers
      - lorentz
      - morley
      - morley-prelude
      - optparse-applicative
      - globacap
      - with-utf8

tests:
  globacap-test:
    <<: *test-common
    source-dirs:
      - test

    dependencies:
      - cleveland
      - globacap
      - lorentz
      - morley
      - morley-ledgers
      - morley-ledgers-test
      - morley-prelude
      - tasty
      - tasty-hspec
      - tasty-hunit-compat

  globacap-nettest:
    <<: *test-common
    source-dirs:
      - nettest

    dependencies:
      - cleveland
      - containers
      - globacap
      - lorentz
      - morley
      - morley-client
      - morley-prelude
      - optparse-applicative
