# SPDX-FileCopyrightText: 2020 Globacap
# SPDX-License-Identifier: MPL-2.0
#
# when updating git dependencies, please run
# nix run -f https://github.com/serokell/scratch/archive/master.tar.gz scripts.update-stack-shas -c update-stack-shas
resolver: lts-15.7

packages:
- .


extra-deps:
- git:
    https://gitlab.com/morley-framework/morley.git
    # ^ CI cannot use ssh, so we use http clone here
  commit:
    0c106a4dde89cdff5101200ac28658badadec74e # master
  # nix-sha256: 18k6mfza4diar2ffpx96awrdl5i3q2p95yk44fy3s8mmxig79bks
  subdirs:
    - code/morley
    - code/indigo
    - code/morley-ledgers
    - code/morley-ledgers-test
    - code/lorentz
    - code/morley-upgradeable
    - code/morley-multisig
    - code/morley-client
    - code/morley-nettest

# Stable parts of morley available from Hackage
- morley-prelude-0.3.0
- tasty-hunit-compat-0.2

# Required by morley
- aeson-options-0.1.0
- base58-bytestring-0.1.0
- hex-text-0.1.0.0
- pretty-terminal-0.1.0.0
- show-type-0.1.1
- git: https://github.com/int-index/caps.git
  commit: c5d61837eb358989b581ed82b1e79158c4823b1b
  # nix-sha256: 0vkhsw1jsyzhk1kimn2g34fms60kms0m9g4r4mr46pavhak5qzsx
# tezos-bake-monitor-lib and its deps which are used in morley-client
- git:
    https://gitlab.com/obsidian.systems/tezos-bake-monitor-lib.git
  commit:
    ed3280836d7d0e87999639520610bf7b6510e743
  # nix-sha256: 1x15x21vd5fmka14br1n95nwwj9fmjgc6x1kwjywi95y9f9zxz3x
  subdirs:
    - tezos-bake-monitor-lib
- witherable-0.3.5
- witherable-class-0
- monoidal-containers-0.6.0.1
- hashing-0.1.0.1@sha256:98861f16791946cdf28e3c7a6ee9ac8b72d546d6e33c569c7087ef18253294e7
- dependent-sum-0.7.1.0
- dependent-sum-template-0.1.0.3
- constraints-extras-0.3.0.2@sha256:bf6884be65958e9188ae3c9e5547abfd6d201df021bff8a4704c2c4fe1e1ae5b
- base-noprelude-4.13.0.0@sha256:3cccbfda38e1422ca5cc436d58858ba51ff9114d2ed87915a6569be11e4e5a90,6842
- fmt-0.6.1.2@sha256:405a1bfc0ba0fd99f6eb1ee71f100045223f79204f961593012f28fd99cd1237,5319
- named-0.3.0.1@sha256:69b9722301201f8ed8abc89c4595e22c746e944bf4cdfafa8b21b14d336b26d1,2233
- vinyl-0.12.1@sha256:43456d4b3009646eee63953cbe539f1f4d0caf8bc3c25e841117e712836508f3,3790

# Required by globacap
- with-utf8-1.0.0.0@sha256:686e47588986d8080451b4e617118b579487dd4e085bba7bb36fac4198c90ae6

nix:
  shell-file: shell.nix
